language: ruby

sudo: false

rvm:
- 2.4.1

os:
- linux
- osx


matrix:
  allow_failures:
  # https://github.com/travis-ci/travis-ci/issues/5361
  - os: osx
    rvm: 2.2.5
  - os: osx
    rvm: 2.3.1
  - os: linux
    rvm: rbx
  exclude:
  - os: osx
    rvm: jruby-1.7
  - os: osx
    rvm: jruby
  - os: osx
    rvm: rbx
